# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db220982037f40f036c04d748571f9a67fdf2f4a0dcc8ec12cf7568702c50bd8bf1d7a0c9684985e8935a46f66692de6e64b6e2f122e05a70e93978d7077654

test:
  secret_key_base: 3236cca2b2d6ceb676c39f4786a2db8af0f0a4e5663c6b8f55c8a8ec8017534bf3b9c638fcd292eab96f381e037c1fd66342e3cd05174efa5d0fdc4f46e2b6f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
